In [1]:
import pandas as pd
df1=pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})
df2=pd.DataFrame({'key':['a','b','d'],'data2':range(3)})

In [2]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [3]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [4]:
pd.merge(df1,df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [5]:
pd.merge(df1,df2,on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [6]:
df3=pd.DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1':range(7)})
df4=pd.DataFrame({'rkey':['a','b','d'],'data2':range(3)})

In [7]:
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [8]:
pd.merge(df1,df2,how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [9]:
pd.merge(df1,df2,how='left')

key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

In [10]:
pd.merge(df1,df2,how='right')

key  data1  data2
0   b    0.0      1
1   b    1.0      1
2   b    6.0      1
3   a    2.0      0
4   a    4.0      0
5   a    5.0      0
6   d    NaN      2

In [11]:
left=pd.DataFrame({'key1':['foo','foo','bar'],'key2':['one','two','one'],'lval':[1,2,3]})
right=pd.DataFrame({'key1':['foo','foo','bar','bar'],'key2':['one','one','one','two'],'rval':[4,5,6,7]})

In [12]:
pd.merge(left,right,on=['key1','key2'],how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [13]:
pd.merge(left,right,on='key1',how='outer')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [14]:
pd.merge(left,right,on='key1',how='outer',suffixes=['_left','_right'])

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [15]:
## merging on index

In [16]:
left1=pd.DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})
right1=pd.DataFrame({'group_val':[3.5,7]},index=['a','b'])

In [17]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  data1  group_val
0   b      0        7.0
1   b      1        7.0
6   b      6        7.0
2   a      2        3.5
4   a      4        3.5
5   a      5        3.5

In [18]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  data1  group_val
0   b      0        7.0
1   b      1        7.0
6   b      6        7.0
2   a      2        3.5
4   a      4        3.5
5   a      5        3.5
3   c      3        NaN

In [19]:
left2=pd.DataFrame([[1,2],[3,4],[5,6]],index=['a','c','e'],columns=['ohio','nevada'])
left2

ohio  nevada
a     1       2
c     3       4
e     5       6

In [20]:
right2=pd.DataFrame([[7,8],[9,10],[11,12],[13,14]],index=['b','c','d','e'],columns=['missouri','alabama'])
right2

missouri  alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [21]:
pd.merge(left2,right2,left_index=True,right_index=True)

ohio  nevada  missouri  alabama
c     3       4         9       10
e     5       6        13       14

In [22]:
pd.merge(left2,right2,left_index=True,right_index=True,how='outer')

ohio  nevada  missouri  alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [23]:
left2.join(right2,how='outer')

ohio  nevada  missouri  alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [24]:
another=pd.DataFrame([[7,8],[9,10],[11,12],[16,17]],index=['a','c','e','f'],columns=['new york','oregon'])

In [25]:
left2.join([right2,another])

ohio  nevada  missouri  alabama  new york  oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [26]:
left2.join([right2,another],how='outer')

ohio  nevada  missouri  alabama  new york  oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0
b   NaN     NaN       7.0      8.0       NaN     NaN
d   NaN     NaN      11.0     12.0       NaN     NaN
f   NaN     NaN       NaN      NaN      16.0    17.0

In [27]:
import numpy as np
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.concatenate([arr,arr],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
## concat

In [30]:
df1=pd.DataFrame(np.random.randn(3,4),columns=['a','b','c','d'])
df2=pd.DataFrame(np.random.randn(2,3),columns=['b','d','a'])

In [31]:
pd.concat([df1,df2])

a         b         c         d
0 -2.187597  0.615975 -0.395457 -0.010856
1 -0.911855  0.672390  1.082850 -0.068483
2 -1.341302 -1.897256 -0.370538 -0.570256
0 -0.557406  0.794189       NaN -1.397610
1  1.430633  1.294170       NaN -1.537363

In [32]:
a=pd.Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])
b=pd.Series(np.arange(len(a)),dtype=np.float,index=['f','e','d','c','b','a'])
b[-1]=np.nan

In [33]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [34]:
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [35]:
np.where(pd.isnull(a),b,a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [36]:
b.combine_first(a)

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [37]:
a.combine_first(b)

f    0.0
e    2.5
d    2.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [38]:
df1=pd.DataFrame({'a':[1.,np.nan,5.,np.nan],
                 'b':[np.nan,2.,np.nan,6.],
                 'c':range(2,18,4)})
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [39]:
df2=pd.DataFrame({'a':[5.,4.,np.nan,3.,7.],
                 'b':[np.nan,3.,4.,6.,8.]})
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [40]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [41]:
data=pd.DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['ohio','colorado'],name='state'),
                 columns=pd.Index(['one','two','three'],name='number'))
data

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [44]:
d1=data.stack()
d1

state     number
ohio      one       0
          two       1
          three     2
colorado  one       3
          two       4
          three     5
dtype: int32

In [46]:
d1.unstack()

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [47]:
d1.unstack(0)

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [48]:
d1.unstack('state')

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [59]:
data2=pd.DataFrame(np.arange(7),index=[['one','two','one','two','one','two','one'],['a','a','b','c','d','d','c']])
data2

0
one a  0
two a  1
one b  2
two c  3
one d  4
two d  5
one c  6

In [61]:
data2.sort_index(0)

0
one a  0
    b  2
    c  6
    d  4
two a  1
    c  3
    d  5

In [63]:
data2.swaplevel(0,1)

0
a one  0
  two  1
b one  2
c two  3
d one  4
  two  5
c one  6

In [72]:
s1=pd.Series([0,1,2,3],index=['a','b','c','d'])
s2=pd.Series([4,5,6],index=['c','d','e'])
data=pd.concat([s1,s2],keys=['a','b'])
data

a  a    0
   b    1
   c    2
   d    3
b  c    4
   d    5
   e    6
dtype: int64

In [73]:
data.unstack()

a    b    c    d    e
a  0.0  1.0  2.0  3.0  NaN
b  NaN  NaN  4.0  5.0  6.0

In [74]:
data.unstack().stack()

a  a    0.0
   b    1.0
   c    2.0
   d    3.0
b  c    4.0
   d    5.0
   e    6.0
dtype: float64

In [75]:
data.unstack().stack(dropna=False)

a  a    0.0
   b    1.0
   c    2.0
   d    3.0
   e    NaN
b  a    NaN
   b    NaN
   c    4.0
   d    5.0
   e    6.0
dtype: float64

In [78]:
result=pd.DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['ohio','colorado'],name='state'),
                 columns=pd.Index(['one','two','three'],name='number'))
result

number    one  two  three
state                    
ohio        0    1      2
colorado    3    4      5

In [82]:
result.stack('number').unstack('state')

state   ohio  colorado
number                
one        0         3
two        1         4
three      2         5

In [84]:
data=pd.read_csv('examples/macrodata.csv')

FileNotFoundError: [Errno 2] File examples/macrodata.csv does not exist: 'examples/macrodata.csv'