In [1]:
import pandas as pd
import numpy as np

In [6]:
data=pd.DataFrame({'x0':[1,2,3,4,5],'x1':[.1,.2,.3,.4,.5],'y':[1.5,-6,1.2,3.,0]})
data

x0   x1    y
0   1  0.1  1.5
1   2  0.2 -6.0
2   3  0.3  1.2
3   4  0.4  3.0
4   5  0.5  0.0

In [7]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [8]:

data.values

array([[ 1. ,  0.1,  1.5],
       [ 2. ,  0.2, -6. ],
       [ 3. ,  0.3,  1.2],
       [ 4. ,  0.4,  3. ],
       [ 5. ,  0.5,  0. ]])

In [9]:
data2=pd.DataFrame(data.values,columns=['one','two','three'])
data2

one  two  three
0  1.0  0.1    1.5
1  2.0  0.2   -6.0
2  3.0  0.3    1.2
3  4.0  0.4    3.0
4  5.0  0.5    0.0

In [10]:
data2['test']=['a','b','c','d','e']
data2

one  two  three test
0  1.0  0.1    1.5    a
1  2.0  0.2   -6.0    b
2  3.0  0.3    1.2    c
3  4.0  0.4    3.0    d
4  5.0  0.5    0.0    e

In [13]:
data2.loc[:,['one','two','three']]

one  two  three
0  1.0  0.1    1.5
1  2.0  0.2   -6.0
2  3.0  0.3    1.2
3  4.0  0.4    3.0
4  5.0  0.5    0.0

In [16]:
data2['cat']=pd.Categorical(['a','c','b','b','a'])

In [17]:
data2

one  two  three test cat
0  1.0  0.1    1.5    a   a
1  2.0  0.2   -6.0    b   c
2  3.0  0.3    1.2    c   b
3  4.0  0.4    3.0    d   b
4  5.0  0.5    0.0    e   a

In [22]:
dummies=pd.get_dummies(data2.cat,prefix='category')
data2=data2.drop(['test','cat'] ,axis=1)

In [23]:
data2.join(dummies)

one  two  three  category_a  category_b  category_c
0  1.0  0.1    1.5           1           0           0
1  2.0  0.2   -6.0           0           0           1
2  3.0  0.3    1.2           0           1           0
3  4.0  0.4    3.0           0           1           0
4  5.0  0.5    0.0           1           0           0

In [24]:
## patsy

In [26]:
data=pd.DataFrame({'x0':[1,2,3,4,5],'x1':[6,7,8,9,10],'y':[12,13,14,15,16]})
data


x0  x1   y
0   1   6  12
1   2   7  13
2   3   8  14
3   4   9  15
4   5  10  16

In [27]:
import patsy

In [28]:
y,X=patsy.dmatrices('y~x0+x1',data)

In [29]:
y

DesignMatrix with shape (5, 1)
   y
  12
  13
  14
  15
  16
  Terms:
    'y' (column 0)

In [30]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  x1
          1   1   6
          1   2   7
          1   3   8
          1   4   9
          1   5  10
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [32]:
np.linalg.lstsq(X,y)

<ipython-input-32-e50ed73de56f>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(X,y)


(array([[ 0.62962963],
        [-1.07407407],
        [ 2.07407407]]),
 array([], dtype=float64),
 2,
 array([1.96597859e+01, 1.86890877e+00, 1.54677697e-16]))

In [34]:
y,X=patsy.dmatrices('y~x0+np.log(np.abs(x1))+1',data)
y

DesignMatrix with shape (5, 1)
   y
  12
  13
  14
  15
  16
  Terms:
    'y' (column 0)

In [35]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1))
          1   1             1.79176
          1   2             1.94591
          1   3             2.07944
          1   4             2.19722
          1   5             2.30259
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1))' (column 2)

In [41]:
y,X=patsy.dmatrices('y~standardize(x0)+center(x1)',data)
y

DesignMatrix with shape (5, 1)
   y
  12
  13
  14
  15
  16
  Terms:
    'y' (column 0)

In [42]:
X

DesignMatrix with shape (5, 3)
  Intercept  standardize(x0)  center(x1)
          1         -1.41421          -2
          1         -0.70711          -1
          1          0.00000           0
          1          0.70711           1
          1          1.41421           2
  Terms:
    'Intercept' (column 0)
    'standardize(x0)' (column 1)
    'center(x1)' (column 2)

In [43]:
new_data=pd.DataFrame({'x0':[6,7,8,9],'x1':[4,3,2,1],'y':[9,8,7,6]})
new_x=patsy.build_design_matrices([X.design_info],new_data)
new_x

[DesignMatrix with shape (4, 3)
   Intercept  standardize(x0)  center(x1)
           1          2.12132          -4
           1          2.82843          -5
           1          3.53553          -6
           1          4.24264          -7
   Terms:
     'Intercept' (column 0)
     'standardize(x0)' (column 1)
     'center(x1)' (column 2)]

In [44]:
y,X=patsy.dmatrices('y~I(x0+x1)',data)
y

DesignMatrix with shape (5, 1)
   y
  12
  13
  14
  15
  16
  Terms:
    'y' (column 0)

In [45]:
X

DesignMatrix with shape (5, 2)
  Intercept  I(x0 + x1)
          1           7
          1           9
          1          11
          1          13
          1          15
  Terms:
    'Intercept' (column 0)
    'I(x0 + x1)' (column 1)

In [46]:
##categorical data and patsy

In [49]:
data=pd.DataFrame({'key1':['a','a','b','b','a','b','a','b'],
                  'key2':[0,1,0,1,0,1,0,0],
                  'v1':[1,2,3,4,5,6,7,8],
                  'v2':[-1,0,2.5,-0.5,4.0,-1.2,0.2,-1.7]})
data

key1  key2  v1   v2
0    a     0   1 -1.0
1    a     1   2  0.0
2    b     0   3  2.5
3    b     1   4 -0.5
4    a     0   5  4.0
5    b     1   6 -1.2
6    a     0   7  0.2
7    b     0   8 -1.7

In [52]:
y,X=patsy.dmatrices('v2~key1',data)
y

DesignMatrix with shape (8, 1)
    v2
  -1.0
   0.0
   2.5
  -0.5
   4.0
  -1.2
   0.2
  -1.7
  Terms:
    'v2' (column 0)

In [53]:
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [54]:
y,X=patsy.dmatrices('v2~key1+0',data)
X
##non numeric becomes categorical automatically

DesignMatrix with shape (8, 2)
  key1[a]  key1[b]
        1        0
        1        0
        0        1
        0        1
        1        0
        0        1
        1        0
        0        1
  Terms:
    'key1' (columns 0:2)

In [55]:
## to consider numerical as categorical
y,X=patsy.dmatrices('v2~C(key2)+0',data)
X

DesignMatrix with shape (8, 2)
  C(key2)[0]  C(key2)[1]
           1           0
           0           1
           1           0
           0           1
           1           0
           0           1
           1           0
           1           0
  Terms:
    'C(key2)' (columns 0:2)

In [56]:
data['key2']=data['key2'].map({0:'zero',1:'one'})
data

key1  key2  v1   v2
0    a  zero   1 -1.0
1    a   one   2  0.0
2    b  zero   3  2.5
3    b   one   4 -0.5
4    a  zero   5  4.0
5    b   one   6 -1.2
6    a  zero   7  0.2
7    b  zero   8 -1.7

In [59]:
y,X=patsy.dmatrices('v2~key1+key2',data)
X

DesignMatrix with shape (8, 3)
  Intercept  key1[T.b]  key2[T.zero]
          1          0             1
          1          0             0
          1          1             1
          1          1             0
          1          0             1
          1          1             0
          1          0             1
          1          1             1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)

In [60]:
y,X=patsy.dmatrices('v2~key1+key2+key1:key2',data)
X

DesignMatrix with shape (8, 4)
  Intercept  key1[T.b]  key2[T.zero]  key1[T.b]:key2[T.zero]
          1          0             1                       0
          1          0             0                       0
          1          1             1                       1
          1          1             0                       0
          1          0             1                       0
          1          1             0                       0
          1          0             1                       0
          1          1             1                       1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)
    'key2' (column 2)
    'key1:key2' (column 3)