In [1]:
import numpy as np

arr=np.arange(3)
arr

array([0, 1, 2])

In [2]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [3]:
arr.repeat([2,3,1])

array([0, 0, 1, 1, 1, 2])

In [4]:
arr=np.random.randn(2,2)
arr

array([[-1.60695834, -0.47545755],
       [-1.23966115,  0.46492809]])

In [5]:
arr.repeat(2,axis=0)

array([[-1.60695834, -0.47545755],
       [-1.60695834, -0.47545755],
       [-1.23966115,  0.46492809],
       [-1.23966115,  0.46492809]])

In [6]:
arr.repeat(2,axis=1)

array([[-1.60695834, -1.60695834, -0.47545755, -0.47545755],
       [-1.23966115, -1.23966115,  0.46492809,  0.46492809]])

In [7]:
arr.repeat(2)

array([-1.60695834, -1.60695834, -0.47545755, -0.47545755, -1.23966115,
       -1.23966115,  0.46492809,  0.46492809])

In [8]:
arr

array([[-1.60695834, -0.47545755],
       [-1.23966115,  0.46492809]])

In [9]:
np.tile(arr,2)

array([[-1.60695834, -0.47545755, -1.60695834, -0.47545755],
       [-1.23966115,  0.46492809, -1.23966115,  0.46492809]])

In [10]:
np.r_[arr,arr]

array([[-1.60695834, -0.47545755],
       [-1.23966115,  0.46492809],
       [-1.60695834, -0.47545755],
       [-1.23966115,  0.46492809]])

In [11]:
np.c_[arr,arr]

array([[-1.60695834, -0.47545755, -1.60695834, -0.47545755],
       [-1.23966115,  0.46492809, -1.23966115,  0.46492809]])

In [12]:
np.tile(arr,(3,2))

array([[-1.60695834, -0.47545755, -1.60695834, -0.47545755],
       [-1.23966115,  0.46492809, -1.23966115,  0.46492809],
       [-1.60695834, -0.47545755, -1.60695834, -0.47545755],
       [-1.23966115,  0.46492809, -1.23966115,  0.46492809],
       [-1.60695834, -0.47545755, -1.60695834, -0.47545755],
       [-1.23966115,  0.46492809, -1.23966115,  0.46492809]])

In [13]:
np.tile(arr,(3,1))

array([[-1.60695834, -0.47545755],
       [-1.23966115,  0.46492809],
       [-1.60695834, -0.47545755],
       [-1.23966115,  0.46492809],
       [-1.60695834, -0.47545755],
       [-1.23966115,  0.46492809]])

In [14]:
arr=np.arange(10)*100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [15]:
inds=[7,1,2,6]
arr[inds]

array([700, 100, 200, 600])

In [16]:
arr.put(inds,42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [17]:
inds=[2,0,2,1]
arr=np.random.randn(2,4)
arr

array([[-0.56623634, -0.2057068 , -0.53394869,  0.36822321],
       [-1.01115864,  0.96441137,  0.98757844,  0.58723702]])

In [18]:
arr.take(inds,axis=1)

array([[-0.53394869, -0.56623634, -0.53394869, -0.2057068 ],
       [ 0.98757844, -1.01115864,  0.98757844,  0.96441137]])

In [19]:
inds=[1,1]
arr.take(inds,axis=0)

array([[-1.01115864,  0.96441137,  0.98757844,  0.58723702],
       [-1.01115864,  0.96441137,  0.98757844,  0.58723702]])

In [20]:
arr=np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
arr_3d=arr[:,np.newaxis,:]
arr_3d.shape

(4, 1, 4)

In [22]:
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [23]:
arr=np.random.randn(3,4,5)
arr

array([[[ 0.1018949 ,  0.00775432, -0.18152666, -0.40229618,
          1.04586066],
        [ 1.27026552,  1.51952923,  0.41906651, -0.74795818,
         -0.25699363],
        [ 0.5544418 ,  1.08059884,  1.57288801, -0.418498  ,
         -0.59929577],
        [ 1.24824438, -0.634995  ,  0.96491682, -0.57886834,
         -0.73656763]],

       [[-1.41525623,  0.638158  ,  1.5812961 ,  0.1175775 ,
          0.15433273],
        [ 0.13639948,  0.69960485,  0.34569608, -0.22950133,
          0.52574728],
        [-0.77615507, -0.00428856, -0.47628578,  1.30651217,
         -0.17019026],
        [ 1.39303581,  1.99922709,  1.22968576, -0.47023626,
          0.34039675]],

       [[-1.12793397,  0.19340986, -0.65520462, -0.75908108,
          1.02521301],
        [-0.476555  , -0.00350533, -0.30729382, -0.53357086,
         -0.54782579],
        [-1.81378154, -0.25174443, -0.29758963, -0.90997812,
          0.38311678],
        [-0.2093905 , -0.52961943, -0.83235415, -0.1706286 ,
          2

In [24]:
#deman along axis2
mean=arr.mean(2)
mean.shape

(3, 4)

In [25]:
demeaned=arr-mean[:,:,np.newaxis]

In [26]:
demeaned.mean(2)

array([[ 0.00000000e+00,  6.66133815e-17,  4.44089210e-17,
        -2.22044605e-17],
       [-1.66533454e-17, -1.11022302e-17, -1.66533454e-17,
         4.44089210e-17],
       [-4.44089210e-17, -5.55111512e-17,  0.00000000e+00,
         0.00000000e+00]])

In [27]:
demeaned.ndim

3

In [28]:
#genarilized demeaning
def demean_axis(arr,axis=0):
    means=arr.arr.mean(axis)
    indexer= [slice(None)]*arr.ndim
    indexer[axis]=np.newaxis
    return arr-mean(indexer)

In [29]:
arr=np.random.randn(3,5)
arr

array([[-0.76743971,  2.25880742,  0.31009636, -0.03521482,  0.23429384],
       [-0.07098067,  1.81909464,  0.12996891, -0.25842757, -1.62239788],
       [ 0.34917654,  1.03347836, -0.37549282,  0.68651544,  0.65648393]])

In [30]:
arr[:,0]

array([-0.76743971, -0.07098067,  0.34917654])

In [31]:
sorted=arr[:,0].sort()

In [32]:
arr

array([[-0.76743971,  2.25880742,  0.31009636, -0.03521482,  0.23429384],
       [-0.07098067,  1.81909464,  0.12996891, -0.25842757, -1.62239788],
       [ 0.34917654,  1.03347836, -0.37549282,  0.68651544,  0.65648393]])

In [33]:
arr2=np.sort(arr)

In [34]:
arr2

array([[-0.76743971, -0.03521482,  0.23429384,  0.31009636,  2.25880742],
       [-1.62239788, -0.25842757, -0.07098067,  0.12996891,  1.81909464],
       [-0.37549282,  0.34917654,  0.65648393,  0.68651544,  1.03347836]])

In [35]:
arr

array([[-0.76743971,  2.25880742,  0.31009636, -0.03521482,  0.23429384],
       [-0.07098067,  1.81909464,  0.12996891, -0.25842757, -1.62239788],
       [ 0.34917654,  1.03347836, -0.37549282,  0.68651544,  0.65648393]])

In [36]:
values=np.array([5,0,1,3,2])
indexer=values.argsort()
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [37]:
values[indexer]

array([0, 1, 2, 3, 5])

In [38]:
arr=np.random.randn(3,5)
arr


array([[ 0.32081628,  0.29246251, -0.03298965,  1.04938178,  2.50453565],
       [ 0.08867975, -0.88350684, -0.77232197,  0.56347341, -0.85843355],
       [-0.21675613,  0.61370684,  1.10126524, -1.0901808 , -0.33015261]])

In [39]:
arr[0]

array([ 0.32081628,  0.29246251, -0.03298965,  1.04938178,  2.50453565])

In [40]:
arr[0]=values
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 0.08867975, -0.88350684, -0.77232197,  0.56347341, -0.85843355],
       [-0.21675613,  0.61370684,  1.10126524, -1.0901808 , -0.33015261]])

In [41]:
arr[0,arr[0].argsort()]

array([0., 1., 2., 3., 5.])

In [42]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 0.08867975, -0.88350684, -0.77232197,  0.56347341, -0.85843355],
       [-0.21675613,  0.61370684,  1.10126524, -1.0901808 , -0.33015261]])

In [43]:
arr[:,arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-0.88350684, -0.77232197, -0.85843355,  0.56347341,  0.08867975],
       [ 0.61370684,  1.10126524, -0.33015261, -1.0901808 , -0.21675613]])

In [44]:
first_name=np.array(['Bob','Jane','Steve','Bill','Barbara'])
last_name=np.array(['Jones','Arnold','Arnold','Jones','Walters'])
sorter=np.lexsort((first_name,last_name))
sorter

array([1, 2, 3, 0, 4], dtype=int64)

In [45]:
sorted=zip(last_name[sorter],first_name[sorter])


In [46]:
for x,y in sorted:
    print(x,y)

Arnold Jane
Arnold Steve
Jones Bill
Jones Bob
Walters Barbara


In [47]:
last_name[sorter]

array(['Arnold', 'Arnold', 'Jones', 'Jones', 'Walters'], dtype='<U7')

In [48]:
np.random.seed(12345)
arr=np.random.randn(20)
arr

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474,
        1.00718936, -1.29622111,  0.27499163,  0.22891288,  1.35291684,
        0.88642934, -2.00163731, -0.37184254,  1.66902531, -0.43856974])

In [49]:
#first 3 elements are the smallest
np.partition(arr,3)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [50]:
indices=np.argpartition(arr,3)
indices

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9], dtype=int64)

In [51]:
arr.take(indices)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [52]:
def mean_distance(x,y):
    nx=len(x)
    result=0
    count=0
    for i in range(len(x)):
                   result +=x[i]-y[i]
                   count +=1
    return result/count
                    

In [53]:
x=np.random.randn(10000000)
y=np.random.randn(10000000)

In [54]:
%timeit mean_distance(x,y).mean()

5.63 s ± 70.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [55]:
def mean_distance_numpy(x,y):
    return (x-y)

In [56]:
%timeit mean_distance_numpy(x,y).mean()

51.9 ms ± 89.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [57]:
## using numba
import numba as nb
mean_distance_numba=nb.jit(mean_distance)

In [58]:
%timeit mean_distance_numba(x,y)

11.8 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [59]:
mmap=np.memmap('mymap',dtype='float64',mode='w+',shape=(10000,10000))
mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [60]:
section=mmap[:5]
section

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [61]:
section[:]=np.random.randn(5,10000)

In [62]:
mmap.flush()

In [63]:
mmap

memmap([[ 1.15399012, -0.14010015, -0.76958656, ...,  0.38385023,
          1.59587314,  0.60136994],
        [ 0.70266709, -2.02765875,  0.33879815, ..., -1.92384027,
          1.55671205, -1.10154042],
        [-1.54364171,  0.35343565, -0.08202607, ...,  1.01483746,
         -1.60385868,  0.78579458],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [64]:
del mmap

In [65]:
mmap1=np.memmap('mymap',dtype='float64',shape=(10000,10000))
mmap1

memmap([[ 1.15399012, -0.14010015, -0.76958656, ...,  0.38385023,
          1.59587314,  0.60136994],
        [ 0.70266709, -2.02765875,  0.33879815, ..., -1.92384027,
          1.55671205, -1.10154042],
        [-1.54364171,  0.35343565, -0.08202607, ...,  1.01483746,
         -1.60385868,  0.78579458],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [66]:
_

memmap([[ 1.15399012, -0.14010015, -0.76958656, ...,  0.38385023,
          1.59587314,  0.60136994],
        [ 0.70266709, -2.02765875,  0.33879815, ..., -1.92384027,
          1.55671205, -1.10154042],
        [-1.54364171,  0.35343565, -0.08202607, ...,  1.01483746,
         -1.60385868,  0.78579458],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [67]:
__

memmap([[ 1.15399012, -0.14010015, -0.76958656, ...,  0.38385023,
          1.59587314,  0.60136994],
        [ 0.70266709, -2.02765875,  0.33879815, ..., -1.92384027,
          1.55671205, -1.10154042],
        [-1.54364171,  0.35343565, -0.08202607, ...,  1.01483746,
         -1.60385868,  0.78579458],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [68]:
_60

memmap([[ 1.15399012, -0.14010015, -0.76958656, ...,  0.38385023,
          1.59587314,  0.60136994],
        [ 0.70266709, -2.02765875,  0.33879815, ..., -1.92384027,
          1.55671205, -1.10154042],
        [-1.54364171,  0.35343565, -0.08202607, ...,  1.01483746,
         -1.60385868,  0.78579458],
        [-1.46497524, -2.44811483,  0.13363636, ..., -1.09092638,
         -0.74154439, -0.85802901],
        [ 1.12511708, -0.50182463,  1.03019708, ...,  2.22537682,
         -0.332711  , -1.57871868]])

In [69]:
_i60

'section=mmap[:5]\nsection'

In [70]:
exec(_i60)

NameError: name 'mmap' is not defined

In [ ]:
_100

In [ ]:
%hist

In [ ]:
%reset

In [ ]:
%hist

In [71]:
%env

{'ALLUSERSPROFILE': 'C:\\ProgramData',
 'APPDATA': 'C:\\Users\\Anu\\AppData\\Roaming',
 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
 'COMPUTERNAME': 'DESKTOP-2G535BV',
 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
 'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
 'HOMEDRIVE': 'C:',
 'HOMEPATH': '\\Users\\Anu',
 'LOCALAPPDATA': 'C:\\Users\\Anu\\AppData\\Local',
 'LOGONSERVER': '\\\\DESKTOP-2G535BV',
 'NUMBER_OF_PROCESSORS': '4',
 'ONEDRIVE': 'C:\\Users\\Anu\\OneDrive',
 'ONEDRIVECONSUMER': 'C:\\Users\\Anu\\OneDrive',
 'OS': 'Windows_NT',
 'PATH': 'C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3

In [72]:
%pwd

'C:\\Users\\Anu\\juypternotebook'

In [73]:
%cd ..
%pwd

C:\Users\Anu


'C:\\Users\\Anu'